# Podfile for HealthPay Keyboard

platform :ios, '14.0'

target 'HealthPayKeyboard' do
  # Uncomment the next line to define a global platform for your project
  # platform :ios, '14.0'

  # Pods for HealthPayKeyboard
  
  # Networking
  pod 'Alamofire', '~> 5.8'
  
  # JSON Parsing
  pod 'SwiftyJSON', '~> 5.0'
  
  # Keychain Storage
  pod 'KeychainAccess', '~> 4.2'
  
  # Logging
  pod 'CocoaLumberjack/Swift', '~> 3.7'
  
  # UI Components
  pod 'SnapKit', '~> 5.6'
  
  # Reactive Programming
  pod 'RxSwift', '~> 6.5'
  pod 'RxCocoa', '~> 6.5'
  
  # Image Caching
  pod 'Kingfisher', '~> 7.8'
  
  # QR Code Generation
  pod 'EFQRCode', '~> 6.2'
  
  # Date Formatting
  pod 'DateToolsSwift', '~> 5.3'

  target 'HealthPayKeyboardTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 7.4'
    pod 'Nimble', '~> 12.1'
  end

end

target 'HealthPayKeyboardExtension' do
  # Pods for HealthPayKeyboardExtension
  
  # Networking
  pod 'Alamofire', '~> 5.8'
  
  # Keychain Storage
  pod 'KeychainAccess', '~> 4.2'
  
  # Logging
  pod 'CocoaLumberjack/Swift', '~> 3.7'
  
  # JSON Parsing
  pod 'SwiftyJSON', '~> 5.0'
  
  # Reactive Programming
  pod 'RxSwift', '~> 6.5'
  pod 'RxCocoa', '~> 6.5'
  
  # QR Code Generation
  pod 'EFQRCode', '~> 6.2'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'COCOAPODS=1',
      ]
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
